
-- CREATE DATABASE dataia;
SET GLOBAL local_infile = 1;
USE dataia;
ALTER DATABASE dataia charset ='hebrew'; -- Y'a que ça qui marche. Va comprendre.
DROP TABLE IF EXISTS client_0;
CREATE TABLE client_0(
    ID VARCHAR(255),
    SHIPPING_MODE VARCHAR(255),
    SHIPPING_PRICE VARCHAR(255),
    WARRANTIES_FLG VARCHAR(255),
    WARRANTIES_PRICE VARCHAR(255),
    CARD_PAYMENT INT,
    COUPON_PAYMENT INT,
    RSP_PAYMENT INT,
    WALLET_PAYMENT INT,
    PRICECLUB_STATUS VARCHAR(255),
    REGISTRATION_DATE INT,
    PURCHASE_COUNT VARCHAR(255),
    BUYER_BIRTHDAY_DATE INT,
    BUYER_DEPARTMENT INT,
    BUYING_DATE VARCHAR(255), -- foutu u overliné
    SELLER_SCORE_COUNT VARCHAR(255),
    SELLER_SCORE_AVERAGE INT,
    SELLER_COUNTRY VARCHAR(255),
    SELLER_DEPARTMENT VARCHAR(255),
    PRODUCT_TYPE VARCHAR(255),
    PRODUCT_FAMILY VARCHAR(255),
    ITEM_PRICE VARCHAR(255),
    `KEY` VARCHAR(255)
);
LOAD DATA LOCAL INFILE '/home/samuel/Projects/Cours/SQL/SQLTP/TP1/Simplon-SQL-TP1/Base_eval.csv' INTO TABLE client_0 
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES;
SET GLOBAL local_infile = 0;


